feat: pago a otras cuentas pospago
wigilabs/miniapp_pagofactura pull request #15
Opened 2023-04-25 14:19 UTC by valen25011

Maquetacion, estructura de pagos otras cuentas y fin, Estilos y funcionalidad

2023-04-25 15:19 UTC, Joredjs requested changes
@valen25011 porfa solucionar los comentarios

2023-04-25 15:19 UTC, Joredjs commented on pages/pagootrascuentas/index.acss
@valen25011 verifica con @jhonnoriega1221 cuales de estas clases están en la librería para usarlas o cuales deberían agregarse a la librería si no están

2023-04-25 15:19 UTC, Joredjs commented on pages/pagootrascuentas/index.js
> +    my.setStorage({
@JdCabarcas95 crear la función para usar el storage dentro del my.js

@valen25011  cuando se cree usar está función del my.js

2023-04-25 15:19 UTC, Joredjs commented on pages/pagootrascuentas/index.js
> +        const responseGetBill = await consumirServicio(urlBill, "POST", JSON.stringify(request));
@valen25011 esta forma de consumir los servicios cambió, ahora se usa el client.js

2023-04-25 15:19 UTC, Joredjs commented on pages/pagootrascuentasfin/index.acss
@valen25011 verifica con @jhonnoriega1221 cuales de estas clases están en la librería para usarlas o cuales deberían agregarse a la librería si no están

2023-04-25 15:19 UTC, Joredjs commented on pages/splash/index.js
@valen25011 esta pantalla no modificarla porfa

2023-04-25 15:19 UTC, Joredjs commented on scripts/utils.js
@valen25011 esta función ya no se usa, para consumir servicios usar el client.js

2023-04-25 15:19 UTC, Joredjs commented on templates/header/index.axml
@valen25011 este template es general para todos porfa no modificarlo por ahora

2023-04-25 15:19 UTC, Joredjs commented on pages/pagootrascuentas/index.json
@valen25011 
- el título que debe salir no se debe cambiar, debe tomarse del app.json
- Para que usas la librería mini-aunti ? Esta creo que no se debería usar

2023-04-25 15:19 UTC, Joredjs commented on package.json
@valen25011 Para que utilizas la librería "mini-antui" ? Si es para popus no deberías usarlo

2023-04-25 22:04 UTC, JdCabarcas95 commented on package.json
Esta librería me aparece deprecada; consultar la version actualizada

2023-04-26 02:25 UTC, valen25011 commented on package.json
Listo

2023-04-26 02:25 UTC, valen25011 commented on package.json
Listo

2023-04-26 02:25 UTC, valen25011 commented on pages/pagootrascuentas/index.json
- Listo
- La usaba para los pop up https://miniprogram.alipay.com/docs/miniprogram/mpdev/extended-component_floating-layer_popup

2023-04-26 02:25 UTC, valen25011 commented on templates/header/index.axml
Hecho

2023-04-26 02:25 UTC, valen25011 commented on scripts/utils.js
Hecho

2023-04-26 02:25 UTC, valen25011 commented on pages/splash/index.js
Listo

2023-04-26 02:25 UTC, valen25011 commented on pages/pagootrascuentasfin/index.acss
Hecho

2023-04-26 02:25 UTC, valen25011 commented on pages/pagootrascuentas/index.js
> +        const responseGetBill = await consumirServicio(urlBill, "POST", JSON.stringify(request));
Mi servicio no estaba creado, pero lo agregué y consumí y quedó funcionando, por fa revisar

2023-04-26 02:25 UTC, valen25011 commented on pages/pagootrascuentas/index.js
> +    my.setStorage({
Queda pendiente la función

2023-04-26 02:25 UTC, valen25011 commented on pages/pagootrascuentas/index.acss
Hecho

2023-04-26 13:19 UTC, Joredjs approved these changes
Se aprueba para poder probar pero solucionar los siguiente para el siguiente PR:

- El servicio consultarDocumento que creaste dentro del archivo endpoint.js ya existe como facturaFija. Usar ese y borrar ese método dentro del endpoint.js y dentro del archivo request.js

2023-04-26 13:23 UTC, merged